# Generated by Django 5.1.7 on 2025-05-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('graduation_info', models.CharField(blank=True, max_length=255, null=True)),
                ('institutions', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='tutor_profiles/')),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('background_check', models.BooleanField(default=False)),
                ('tuition_fee', models.PositiveIntegerField(default=0)),
                ('subjects', models.TextField(blank=True, null=True)),
                ('short_bio', models.TextField(blank=True, null=True)),
                ('accepted_terms', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
