# Generated by Django 5.1.7 on 2025-05-02 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='background_check',
        ),
    ]
