# Generated by Django 5.1.7 on 2025-05-02 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_remove_tutor_background_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='accepted_terms',
        ),
    ]
