# Generated by Django 5.1.7 on 2025-05-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_remove_tutor_accepted_terms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='phone_number',
            new_name='contact_number',
        ),
        migrations.AddField(
            model_name='tutor',
            name='medium',
            field=models.CharField(choices=[('Bangla', 'Bangla'), ('English', 'English'), ('Bangla/English', 'Bangla/English')], default='Bangla', max_length=20),
        ),
    ]
