# Generated by Django 5.1.7 on 2025-05-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_rename_phone_number_tutor_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='graduation_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='institutions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='short_bio',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='subjects',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
