# Generated by Django 5.1.7 on 2025-05-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tutor_request_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('medium', models.CharField(choices=[('Bangla', 'Bangla'), ('English', 'English')], default='Bangla', max_length=20)),
                ('student_class', models.CharField(choices=[('Class 1', 'Class 1'), ('Class 2', 'Class 2'), ('Class 3', 'Class 3'), ('Class 4', 'Class 4'), ('Class 5', 'Class 5'), ('Class 6', 'Class 6'), ('Class 7', 'Class 7'), ('Class 8', 'Class 8'), ('Class 9', 'Class 9'), ('Class 10', 'Class 10'), ('HSC 1st Year', 'HSC 1st Year'), ('HSC 2nd Year', 'HSC 2nd Year')], default='class 10', max_length=30)),
                ('preferred_tutor', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('MALE/FEMALE', 'MALE/FEMALE')], default='MALE', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tutoring_days', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
