# Generated by Django 5.1.6 on 2025-04-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor_request_post',
            name='image',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
