# Generated by Django 5.1.6 on 2025-04-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_tutor_request_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor_request_post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
