# Generated by Django 5.1.6 on 2025-04-24 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_tutor_request_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor_request_post',
            name='image',
        ),
    ]
