# Generated by Django 5.2 on 2025-04-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_tutor_request_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor_request_post',
            name='phone',
        ),
        migrations.AddField(
            model_name='tutor_request_post',
            name='contact_number',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tutor_request_post',
            name='preffered_tutor',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tutor_request_post',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tutor_request_post',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tutor_request_post',
            name='tutoring_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tutor_request_post',
            name='medium',
            field=models.CharField(blank=True, choices=[('Bangla', 'Bangla'), ('English', 'English')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tutor_request_post',
            name='student_class',
            field=models.CharField(blank=True, choices=[('Class 1', 'Class 1'), ('Class 2', 'Class 2'), ('Class 3', 'Class 3'), ('Class 4', 'Class 4'), ('Class 5', 'Class 5'), ('Class 6', 'Class 6'), ('Class 7', 'Class 7'), ('Class 8', 'Class 8'), ('Class 9', 'Class 9'), ('Class 10', 'Class 10'), ('HSC 1st Year', 'HSC 1st Year'), ('HSC 2nd Year', 'HSC 2nd Year')], max_length=30, null=True),
        ),
    ]
