# Generated by Django 5.2 on 2025-04-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_tutor_request_post_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor_request_post',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
