# Generated by Django 5.2 on 2025-04-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_tutor_request_post_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor_request_post',
            name='preffered_tutor',
        ),
        migrations.AddField(
            model_name='tutor_request_post',
            name='preferred_tutor',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tutor_request_post',
            name='medium',
            field=models.CharField(choices=[('Bangla', 'Bangla'), ('English', 'English')], default='Bangla', max_length=20),
        ),
        migrations.AlterField(
            model_name='tutor_request_post',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tutor_request_post',
            name='student_class',
            field=models.CharField(choices=[('Class 1', 'Class 1'), ('Class 2', 'Class 2'), ('Class 3', 'Class 3'), ('Class 4', 'Class 4'), ('Class 5', 'Class 5'), ('Class 6', 'Class 6'), ('Class 7', 'Class 7'), ('Class 8', 'Class 8'), ('Class 9', 'Class 9'), ('Class 10', 'Class 10'), ('HSC 1st Year', 'HSC 1st Year'), ('HSC 2nd Year', 'HSC 2nd Year')], default='class 10', max_length=30),
        ),
    ]
