# Generated by Django 5.1.7 on 2025-05-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_tutor_request_post_preffered_tutor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor_request_post',
            old_name='area',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='tutor_request_post',
            name='preferred_tutor',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('MALE/FEMALE', 'MALE/FEMALE')], default='MALE', max_length=20),
        ),
    ]
