# Generated by Django 5.1.7 on 2025-05-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/defaultprofile.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
