# Generated by Django 5.1.7 on 2025-05-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/defaultprofile.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
