# Generated by Django 5.1.7 on 2025-05-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/defaultprofile.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
