# Generated by Django 5.1.6 on 2025-04-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Skill', 'Skill Devolopment')], max_length=50),
        ),
    ]
