# Generated by Django 5.1.6 on 2025-05-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_academicprogramvideo_admissionprogram_skillvideo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicprogramvideo',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='skillvideo',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='admissionprogram',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
